import React, { useEffect, useState, useCallback } from "react";
import { 
  FaTrash, FaPlus, FaHistory, FaCheckCircle, 
  FaSearch, FaFilePdf, FaEdit, FaTimes 
} from "react-icons/fa";
import jsPDF from "jspdf"; 
import autoTable from "jspdf-autotable";

const ReportsPage = () => {
  const [amount, setAmount] = useState("");
  const [description, setDescription] = useState("");
  const [type, setType] = useState("Income");

  // Filter & Summary States
  const currentYear = new Date().getFullYear().toString();
  const [selectedYear, setSelectedYear] = useState(currentYear);
  const [selectedQuarter, setSelectedQuarter] = useState("Quarter 1 (Jan - Mar)");
  const [totals, setTotals] = useState({ gross: 0, expenses: 0, net: 0 });
  
  const [submissions, setSubmissions] = useState([]);
  const [filteredSubmissions, setFilteredSubmissions] = useState([]);
  const [showSuccessDialog, setShowSuccessDialog] = useState(false);

  // Edit States
  const [editingItem, setEditingItem] = useState(null);
  const [editForm, setEditForm] = useState({ date: "", description: "", type: "Income", amount: "" });

  const getTodayString = () => new Date().toISOString().split("T")[0];
  const today = getTodayString();
  const [selectedDate, setSelectedDate] = useState(today);
  
  // User Data from LocalStorage
  const user = JSON.parse(localStorage.getItem("user") || "{}");
  const displayName = user.firstName || user.name || "User";

  const fetchSubmissions = useCallback(async () => {
    try {
      const res = await fetch("http://localhost:5000/api/earnings");
      if (!res.ok) throw new Error("Server error");
      const data = await res.json();
      setSubmissions(data);
      applyFilter(data, selectedYear, selectedQuarter);
    } catch (err) {
      console.error("Fetch error:", err);
    }
  }, [selectedYear, selectedQuarter]);

  useEffect(() => {
    fetchSubmissions();
  }, [fetchSubmissions]);

  const calculateTotals = (data) => {
    const gross = data.filter(item => item.type === "Income").reduce((sum, item) => sum + Number(item.amount), 0);
    const expenses = data.filter(item => item.type === "Expense").reduce((sum, item) => sum + Number(item.amount), 0);
    setTotals({ gross, expenses, net: gross - expenses });
  };

  const applyFilter = (data, year, quarter) => {
    const quarterMap = {
      "Quarter 1 (Jan - Mar)": [0, 1, 2],
      "Quarter 2 (Apr - Jun)": [3, 4, 5],
      "Quarter 3 (Jul - Sep)": [6, 7, 8],
      "Quarter 4 (Oct - Dec)": [9, 10, 11],
    };
    const allowedMonths = quarterMap[quarter];
    const filtered = data.filter((item) => {
      const itemDate = new Date(item.date);
      return itemDate.getFullYear().toString() === year && allowedMonths.includes(itemDate.getMonth());
    });
    setFilteredSubmissions(filtered);
    calculateTotals(filtered);
  };

  const handleGenerateReport = () => {
    applyFilter(submissions, selectedYear, selectedQuarter);
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("Farm Ops Financial Report", 14, 20);
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(`${selectedQuarter} ${selectedYear}`, 14, 28);
    
    doc.setLineWidth(0.5);
    doc.line(14, 33, 196, 33); 

    doc.setFontSize(10);
    doc.text(`Generated by: ${user.email || displayName}`, 14, 42);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 14, 48);
    
    const tableRows = filteredSubmissions.map(item => [
      new Date(item.date).toLocaleDateString(),
      item.description,
      item.type,
      `P${item.amount.toLocaleString()}`,
      item.role || "N/A"
    ]);

    autoTable(doc, {
      startY: 55,
      head: [['Date', 'Description', 'Type', 'Amount', 'Role']],
      body: tableRows,
      headStyles: { fillGray: [78, 115, 223], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    const finalY = doc.lastAutoTable.finalY + 15;
    doc.setFillColor(245, 247, 249);
    doc.rect(14, finalY, 80, 40, 'F');
    doc.setDrawColor(220, 220, 220);
    doc.rect(14, finalY, 80, 40, 'S');

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Financial Summary", 18, finalY + 8);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Gross Income: P${totals.gross.toLocaleString()}`, 18, finalY + 18);
    doc.text(`Total Expenses: P${totals.expenses.toLocaleString()}`, 18, finalY + 26);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(45, 138, 100); 
    doc.text(`Net Income: P${totals.net.toLocaleString()}`, 18, finalY + 34);

    doc.save(`FarmOps_Report_${selectedQuarter.replace(/ /g, "_")}.pdf`);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!amount || !selectedDate) return;
    try {
      const response = await fetch("http://localhost:5000/api/earnings", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          amount: Number(amount),
          date: selectedDate,
          description,
          type,
          encodedBy: displayName,
          role: user.role
        })
      });
      if (response.ok) {
        setAmount(""); setDescription(""); setSelectedDate(today);
        await fetchSubmissions();
        setShowSuccessDialog(true);
        setTimeout(() => setShowSuccessDialog(false), 3000);
      }
    } catch (err) { console.error("Submit error:", err); }
  };

  const deleteRecord = async (id) => {
    if (window.confirm("Are you sure you want to delete this record?")) {
      try {
        const res = await fetch(`http://localhost:5000/api/earnings/${id}`, { method: "DELETE" });
        if (res.ok) fetchSubmissions();
      } catch (err) { console.error("Delete error:", err); }
    }
  };

  const openEditModal = (item) => {
    setEditingItem(item._id);
    setEditForm({
      date: new Date(item.date).toISOString().split("T")[0],
      description: item.description,
      type: item.type,
      amount: item.amount
    });
  };

  const handleUpdate = async () => {
    try {
      const response = await fetch(`http://localhost:5000/api/earnings/${editingItem}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(editForm)
      });
      if (response.ok) {
        setEditingItem(null);
        await fetchSubmissions();
      }
    } catch (err) { console.error("Update error:", err); }
  };

  const styles = {
    // Ginawang transparent ang container para makita ang background image ng system
    container: { padding: "20px", fontFamily: "'Inter', sans-serif", backgroundColor: "transparent", minHeight: "100vh" },
    // Retain white bg para sa cards at containers
    card: { background: "#fff", padding: "20px", borderRadius: "15px", boxShadow: "0 4px 12px rgba(0,0,0,0.05)", border: "1px solid #e2e8f0", marginBottom: "20px" },
    summaryBox: (borderColor) => ({ background: "#fff", padding: "20px", borderRadius: "12px", borderLeft: `6px solid ${borderColor}`, boxShadow: "0 2px 8px rgba(0,0,0,0.03)", flex: "1 1 200px" }),
    // Retain white bg para sa inputs at placeholders
    input: { padding: "10px", borderRadius: "8px", border: "1px solid #e2e8f0", width: "100%", marginBottom: "10px", backgroundColor: "#fff" },
    primaryBtn: (bgColor) => ({ background: bgColor, color: "white", border: "none", padding: "10px 20px", borderRadius: "8px", cursor: "pointer", fontWeight: "600", display: "flex", alignItems: "center", gap: "8px" }),
    tableContainer: { overflowX: "auto" },
    table: { width: "100%", borderCollapse: "collapse", minWidth: "800px" },
    th: { background: "#f8fafc", padding: "12px", borderBottom: "2px solid #edf2f7", color: "#64748b", fontSize: "0.8rem", textAlign: "left", textTransform: "uppercase" },
    td: { padding: "12px", borderBottom: "1px solid #f1f5f9", fontSize: "0.9rem", color: "#334155" },
    badge: (type) => ({ padding: "4px 8px", borderRadius: "6px", fontSize: "0.7rem", fontWeight: "700", backgroundColor: type === "Income" ? "#dcfce7" : "#fee2e2", color: type === "Income" ? "#15803d" : "#ef4444" }),
    modalOverlay: { position: "fixed", top: 0, left: 0, width: "100%", height: "100%", background: "rgba(0,0,0,0.5)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 1000 }
  };

  return (
    <div style={styles.container}>
      {showSuccessDialog && (
        <div style={{ position: "fixed", top: "20px", right: "20px", background: "#2d8a64", color: "white", padding: "15px 25px", borderRadius: "8px", zIndex: 2000 }}>
          <FaCheckCircle /> Saved Successfully!
        </div>
      )}

      {editingItem && (
        <div style={styles.modalOverlay}>
          <div style={{...styles.card, width: "400px"}}>
            <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "15px" }}>
              <h3>Edit Record</h3>
              <FaTimes style={{ cursor: "pointer" }} onClick={() => setEditingItem(null)} />
            </div>
            <input style={styles.input} type="date" max={today} value={editForm.date} onChange={(e) => setEditForm({...editForm, date: e.target.value})} />
            <input style={styles.input} type="text" value={editForm.description} onChange={(e) => setEditForm({...editForm, description: e.target.value})} />
            <select style={styles.input} value={editForm.type} onChange={(e) => setEditForm({...editForm, type: e.target.value})}><option value="Income">Income</option><option value="Expense">Expense</option></select>
            <input style={styles.input} type="number" value={editForm.amount} onChange={(e) => setEditForm({...editForm, amount: e.target.value})} />
            <button onClick={handleUpdate} style={styles.primaryBtn("#4e73df")}>Update</button>
          </div>
        </div>
      )}

      {/* Summary Section */}
      <div style={{ display: "flex", gap: "15px", flexWrap: "wrap", marginBottom: "20px" }}>
        <div style={styles.summaryBox("#57bc90")}><h4>Gross Income</h4><p style={{fontSize: "1.5rem", fontWeight: "bold"}}>P{totals.gross.toLocaleString()}</p></div>
        <div style={styles.summaryBox("#ff6b6b")}><h4>Expenses</h4><p style={{fontSize: "1.5rem", fontWeight: "bold"}}>P{totals.expenses.toLocaleString()}</p></div>
        <div style={styles.summaryBox("#4e73df")}><h4>Net Income</h4><p style={{fontSize: "1.5rem", fontWeight: "bold"}}>P{totals.net.toLocaleString()}</p></div>
      </div>

      <div style={styles.card}>
        <div style={{display: "flex", gap: "10px", flexWrap: "wrap"}}>
          <select style={{...styles.input, width: "150px"}} value={selectedYear} onChange={(e) => setSelectedYear(e.target.value)}>
            <option value="2024">2024</option>
            <option value="2025">2025</option>
            <option value="2026">2026</option>
          </select>
          <select style={{...styles.input, width: "220px"}} value={selectedQuarter} onChange={(e) => setSelectedQuarter(e.target.value)}>
            <option value="Quarter 1 (Jan - Mar)">Quarter 1 (Jan - Mar)</option>
            <option value="Quarter 2 (Apr - Jun)">Quarter 2 (Apr - Jun)</option>
            <option value="Quarter 3 (Jul - Sep)">Quarter 3 (Jul - Sep)</option>
            <option value="Quarter 4 (Oct - Dec)">Quarter 4 (Oct - Dec)</option>
          </select>
          <button style={styles.primaryBtn("#4e73df")} onClick={handleGenerateReport}><FaSearch /> Filter</button>
          <button style={styles.primaryBtn("#57bc90")} onClick={exportToPDF}><FaFilePdf /> PDF</button>
        </div>
      </div>

      <div style={styles.card}>
        <h3 style={{marginBottom: "15px"}}><FaPlus /> Add Daily Report</h3>
        <form onSubmit={handleSubmit} style={{display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: "10px"}}>
          <input style={styles.input} type="date" max={today} value={selectedDate} onChange={(e) => setSelectedDate(e.target.value)} />
          <input style={styles.input} type="text" placeholder="Description" value={description} onChange={(e) => setDescription(e.target.value)} />
          <select style={styles.input} value={type} onChange={(e) => setType(e.target.value)}><option value="Income">Income</option><option value="Expense">Expense</option></select>
          <input style={styles.input} type="number" placeholder="Amount" value={amount} onChange={(e) => setAmount(e.target.value)} />
          <button type="submit" style={{...styles.primaryBtn("#57bc90"), width: "100%"}}>Submit</button>
        </form>
      </div>

      <div style={styles.card}>
        <h3 style={{marginBottom: "15px"}}><FaHistory /> History</h3>
        <div style={styles.tableContainer}>
          <table style={styles.table}>
            <thead>
              <tr>
                <th style={styles.th}>Date</th>
                <th style={styles.th}>Description</th>
                <th style={styles.th}>Type</th>
                <th style={styles.th}>Amount</th>
                <th style={styles.th}>Added By</th>
                <th style={styles.th}>Action</th>
              </tr>
            </thead>
            <tbody>
              {filteredSubmissions.map((item) => (
                <tr key={item._id}>
                  <td style={styles.td}>{new Date(item.date).toLocaleDateString()}</td>
                  <td style={styles.td}>{item.description}</td>
                  <td style={styles.td}><span style={styles.badge(item.type)}>{item.type}</span></td>
                  <td style={styles.td}>P{item.amount.toLocaleString()}</td>
                  <td style={styles.td}>{item.role} - {item.encodedBy}</td>
                  <td style={styles.td}>
                    <div style={{display: "flex", gap: "12px", alignItems: "center"}}>
                      <FaEdit 
                        style={{color: "#4e73df", cursor: "pointer", fontSize: "1.1rem"}} 
                        onClick={() => openEditModal(item)} 
                      />
                      <FaTrash 
                        style={{color: "#ef4444", cursor: "pointer", fontSize: "1.1rem"}} 
                        onClick={() => deleteRecord(item._id)} 
                      />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ReportsPage;