import React, { useEffect, useState, useCallback } from "react";
import { FaTrash, FaPlus, FaHistory, FaCheckCircle, FaSearch, FaFilePdf, FaEdit, FaTimes } from "react-icons/fa";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const ReportsPage = () => {
  const [amount, setAmount] = useState("");
  const [description, setDescription] = useState("");
  const [type, setType] = useState("Income");

  // Filter & Summary States
  const [selectedYear, setSelectedYear] = useState("2026");
  const [selectedQuarter, setSelectedQuarter] = useState("Quarter 1 (Jan - Mar)");
  const [totals, setTotals] = useState({ gross: 0, expenses: 0, net: 0 });
  
  const [submissions, setSubmissions] = useState([]);
  const [filteredSubmissions, setFilteredSubmissions] = useState([]);
  const [showSuccessDialog, setShowSuccessDialog] = useState(false);

  // Edit States
  const [editingItem, setEditingItem] = useState(null);
  const [editForm, setEditForm] = useState({ date: "", description: "", type: "Income", amount: "" });

  const getTodayString = () => {
    const today = new Date();
    return today.toISOString().split("T")[0];
  };

  const today = getTodayString();
  const [selectedDate, setSelectedDate] = useState(today);
  const user = JSON.parse(localStorage.getItem("user"));

  const fetchSubmissions = useCallback(async () => {
    try {
      const res = await fetch("http://localhost:5000/api/earnings");
      if (!res.ok) throw new Error("Server error");

      const data = await res.json();
      const userRecords = data.filter(item => item.employeeEmail === user?.email);
      setSubmissions(userRecords);
      setFilteredSubmissions(userRecords);
      calculateTotals(userRecords); 
    } catch (err) {
      console.error("Fetch error:", err);
    }
  }, [user?.email]);

  useEffect(() => {
    if (user?.email) fetchSubmissions();
  }, [fetchSubmissions, user?.email]);

  const calculateTotals = (data) => {
    const gross = data
      .filter(item => item.type === "Income")
      .reduce((sum, item) => sum + Number(item.amount), 0);
    
    const expenses = data
      .filter(item => item.type === "Expense")
      .reduce((sum, item) => sum + Number(item.amount), 0);
    
    setTotals({ gross, expenses, net: gross - expenses });
  };

  const handleGenerateReport = () => {
    const quarterMap = {
      "Quarter 1 (Jan - Mar)": [0, 1, 2],
      "Quarter 2 (Apr - Jun)": [3, 4, 5],
      "Quarter 3 (Jul - Sep)": [6, 7, 8],
      "Quarter 4 (Oct - Dec)": [9, 10, 11],
    };

    const allowedMonths = quarterMap[selectedQuarter];

    const filtered = submissions.filter((item) => {
      const itemDate = new Date(item.date);
      const itemYear = itemDate.getFullYear().toString();
      const itemMonth = itemDate.getMonth();
      return itemYear === selectedYear && allowedMonths.includes(itemMonth);
    });

    setFilteredSubmissions(filtered);
    calculateTotals(filtered); 
  };

  const exportToPDF = () => {
    if (filteredSubmissions.length === 0) {
      alert("Walang data para sa napiling period.");
      return;
    }

    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40); 
    doc.setFont(undefined, 'bold');
    doc.text("Farm Ops Financial Report", 14, 22);
    
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`${selectedQuarter} ${selectedYear}`, 14, 30);
    
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 35, 196, 35);

    // Meta-info
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by: ${user?.email || "N/A"}`, 14, 42);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 14, 47);

    // Table Mapping
    const tableRows = filteredSubmissions.map(item => [
      new Date(item.date).toLocaleDateString(),
      item.description || "-",
      item.type,
      `P${Number(item.amount).toLocaleString()}`,
      item.role || "Employee"
    ]);

    autoTable(doc, {
      startY: 55,
      head: [['Date', 'Description', 'Type', 'Amount', 'Role']],
      body: tableRows,
      theme: 'grid',
      headStyles: { fillColor: [78, 115, 223], fontSize: 11, halign: 'center' },
      columnStyles: {
        3: { halign: 'right' },
      },
      styles: { fontSize: 10, cellPadding: 3 },
      didParseCell: function (data) {
        // Kulay ng Type column (Income = Green, Expense = Red)
        if (data.section === 'body' && data.column.index === 2) {
          if (data.cell.raw === 'Income') {
            data.cell.styles.textColor = [46, 125, 50];
          } else {
            data.cell.styles.textColor = [198, 40, 40];
          }
        }
      }
    });

    const finalY = doc.lastAutoTable.finalY + 15;
    
    // Summary Box
    doc.setDrawColor(220, 220, 220);
    doc.setFillColor(248, 249, 252);
    doc.rect(14, finalY, 80, 40, 'FD');

    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.setFont(undefined, 'bold');
    doc.text("Financial Summary", 18, finalY + 10);
    
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Gross Income: P${totals.gross.toLocaleString()}`, 18, finalY + 18);
    doc.text(`Total Expenses: P${totals.expenses.toLocaleString()}`, 18, finalY + 25);
    
    // Fix for Net Income color
    if (totals.net >= 0) {
      doc.setTextColor(46, 125, 50); // Green
    } else {
      doc.setTextColor(198, 40, 40); // Red
    }
    
    doc.setFont(undefined, 'bold');
    doc.text(`Net Income: P${totals.net.toLocaleString()}`, 18, finalY + 34);

    doc.save(`Detailed_Report_${selectedYear}.pdf`);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!amount || !selectedDate) return;
    try {
      const response = await fetch("http://localhost:5000/api/earnings", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          employeeEmail: user.email,
          amount: Number(amount),
          date: selectedDate,
          description,
          type,
          encodedBy: user.email,
          role: user.role
        })
      });
      if (response.ok) {
        setAmount(""); setDescription(""); setType("Income"); setSelectedDate(today);
        await fetchSubmissions();
        setShowSuccessDialog(true);
        setTimeout(() => setShowSuccessDialog(false), 3000);
      }
    } catch (err) { console.error("Submit error:", err); }
  };

  const deleteRecord = async (id) => {
    if (window.confirm("Are you sure you want to delete this record?")) {
      await fetch(`http://localhost:5000/api/earnings/${id}`, { method: "DELETE" });
      fetchSubmissions();
    }
  };

  const openEditModal = (item) => {
    setEditingItem(item._id);
    setEditForm({
      date: new Date(item.date).toISOString().split("T")[0],
      description: item.description,
      type: item.type,
      amount: item.amount
    });
  };

  const handleUpdate = async () => {
    try {
      const response = await fetch(`http://localhost:5000/api/earnings/${editingItem}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(editForm)
      });
      if (response.ok) {
        setEditingItem(null);
        await fetchSubmissions();
      }
    } catch (err) { console.error("Update error:", err); }
  };

  const styles = {
    container: { padding: "20px", fontFamily: "'Inter', sans-serif", color: "#333" },
    card: { background: "#fff", padding: "20px", borderRadius: "12px", boxShadow: "0 4px 6px rgba(0,0,0,0.05)", marginBottom: "20px" },
    title: { fontSize: "17px", fontWeight: "bold", marginBottom: "20px", color: "#1f2933", display: "flex", alignItems: "center", gap: "10px" },
    summaryGrid: { display: "flex", flexWrap: "wrap", gap: "15px", marginBottom: "20px" },
    summaryBox: { flex: "1 1 200px", padding: "15px", borderRadius: "8px", background: "#f8f9fc", borderLeft: "4px solid #4e73df" },
    formGrid: { display: "flex", flexWrap: "wrap", gap: "15px", alignItems: "flex-end" },
    inputGroup: { display: "flex", flexDirection: "column", gap: "5px", flex: "1 1 150px" },
    label: { fontSize: "12px", fontWeight: "600", color: "#666" },
    input: { padding: "10px", borderRadius: "6px", border: "1px solid #ddd", fontSize: "14px", width: "100%", boxSizing: "border-box" },
    submitBtn: { background: "#57b894", color: "white", border: "none", padding: "11px 20px", borderRadius: "6px", cursor: "pointer", fontWeight: "bold", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px", width: "100%" },
    tableWrapper: { width: "100%", overflowX: "auto" },
    table: { width: "100%", borderCollapse: "collapse", marginTop: "10px", minWidth: "700px" },
    th: { background: "#f8f9fc", padding: "12px", borderBottom: "2px solid #e3e6f0", color: "#4e73df", fontSize: "12px", textTransform: "uppercase", textAlign: "left" },
    td: { padding: "12px", borderBottom: "1px solid #eee", fontSize: "13px" },
    badgeIncome: { background: "#e1f5fe", color: "#0288d1", padding: "3px 8px", borderRadius: "4px", fontSize: "11px", fontWeight: "bold" },
    badgeExpense: { background: "#ffebee", color: "#d32f2f", padding: "3px 8px", borderRadius: "4px", fontSize: "11px", fontWeight: "bold" },
    actionBtn: { border: "none", background: "none", cursor: "pointer", fontSize: "18px", padding: "4px", display: "flex", alignItems: "center" },
    modalOverlay: { position: "fixed", top: 0, left: 0, width: "100%", height: "100%", background: "rgba(0,0,0,0.5)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 2000 },
    modal: { background: "white", padding: "25px", borderRadius: "10px", width: "400px", boxShadow: "0 10px 25px rgba(0,0,0,0.2)" }
  };

  return (
    <div style={styles.container}>
      {showSuccessDialog && (
        <div style={{ position: "fixed", top: "20px", right: "20px", background: "#57b894", color: "white", padding: "15px 25px", borderRadius: "8px", zIndex: 1000, display: "flex", alignItems: "center", gap: "10px" }}>
          <FaCheckCircle /> Report submitted successfully!
        </div>
      )}

      {/* Edit Modal */}
      {editingItem && (
        <div style={styles.modalOverlay}>
          <div style={styles.modal}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
              <h3 style={{ margin: 0 }}>Edit Record</h3>
              <FaTimes style={{ cursor: "pointer", color: "#888" }} onClick={() => setEditingItem(null)} />
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "15px" }}>
              <div><label style={styles.label}>Date</label><input style={styles.input} type="date" value={editForm.date} onChange={(e) => setEditForm({...editForm, date: e.target.value})} /></div>
              <div><label style={styles.label}>Description</label><input style={styles.input} type="text" value={editForm.description} onChange={(e) => setEditForm({...editForm, description: e.target.value})} /></div>
              <div><label style={styles.label}>Type</label><select style={styles.input} value={editForm.type} onChange={(e) => setEditForm({...editForm, type: e.target.value})}><option value="Income">Income</option><option value="Expense">Expense</option></select></div>
              <div><label style={styles.label}>Amount</label><input style={styles.input} type="number" value={editForm.amount} onChange={(e) => setEditForm({...editForm, amount: e.target.value})} /></div>
              <button onClick={handleUpdate} style={{ ...styles.submitBtn }}>Save Changes</button>
            </div>
          </div>
        </div>
      )}

      {/* Filter & Summary Section */}
      <div style={styles.card}>
        <div style={styles.title}><FaSearch /> Report Filters & Summary</div>
        
        <div style={styles.summaryGrid}>
          <div style={styles.summaryBox}>
            <div style={styles.label}>Gross Income</div>
            <div style={{ fontSize: "20px", fontWeight: "bold", color: "#57b894" }}>₱{totals.gross.toLocaleString()}</div>
          </div>
          <div style={{ ...styles.summaryBox, borderLeftColor: "#ff6b6b" }}>
            <div style={styles.label}>Total Expenses</div>
            <div style={{ fontSize: "20px", fontWeight: "bold", color: "#ff6b6b" }}>₱{totals.expenses.toLocaleString()}</div>
          </div>
          <div style={{ ...styles.summaryBox, borderLeftColor: totals.net >= 0 ? "#4e73df" : "#d32f2f" }}>
            <div style={styles.label}>Net Income</div>
            <div style={{ fontSize: "20px", fontWeight: "bold", color: totals.net >= 0 ? "#4e73df" : "#d32f2f" }}>₱{totals.net.toLocaleString()}</div>
          </div>
        </div>

        {/* YEAR AND QUARTER SELECTORS ARE BACK HERE */}
        <div style={{ display: "flex", gap: "20px", marginBottom: "20px", flexWrap: "wrap" }}>
          <div style={styles.inputGroup}>
            <label style={styles.label}>Year</label>
            <select style={styles.input} value={selectedYear} onChange={(e) => setSelectedYear(e.target.value)}>
              <option value="2024">2024</option>
              <option value="2025">2025</option>
              <option value="2026">2026</option>
            </select>
          </div>
          <div style={styles.inputGroup}>
            <label style={styles.label}>Quarter</label>
            <select style={styles.input} value={selectedQuarter} onChange={(e) => setSelectedQuarter(e.target.value)}>
              <option value="Quarter 1 (Jan - Mar)">Quarter 1 (Jan - Mar)</option>
              <option value="Quarter 2 (Apr - Jun)">Quarter 2 (Apr - Jun)</option>
              <option value="Quarter 3 (Jul - Sep)">Quarter 3 (Jul - Sep)</option>
              <option value="Quarter 4 (Oct - Dec)">Quarter 4 (Oct - Dec)</option>
            </select>
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
           <button style={{...styles.submitBtn, background: "#4e73df"}} onClick={handleGenerateReport}><FaSearch /> Generate</button>
           <button style={{...styles.submitBtn, background: "#57b894"}} onClick={exportToPDF}><FaFilePdf /> Export PDF</button>
        </div>
      </div>

      {/* Submission Form */}
      <div style={styles.card}>
        <div style={styles.title}><FaPlus /> Submit Daily Report</div>
        <form onSubmit={handleSubmit} style={styles.formGrid}>
          <div style={styles.inputGroup}><label style={styles.label}>Date</label><input style={styles.input} type="date" value={selectedDate} onChange={(e) => setSelectedDate(e.target.value)} /></div>
          <div style={styles.inputGroup}><label style={styles.label}>Description</label><input style={styles.input} type="text" value={description} placeholder="e.g. Sales" onChange={(e) => setDescription(e.target.value)} /></div>
          <div style={styles.inputGroup}>
            <label style={styles.label}>Type</label>
            <select style={styles.input} value={type} onChange={(e) => setType(e.target.value)}>
              <option value="Income">Income</option>
              <option value="Expense">Expense</option>
            </select>
          </div>
          <div style={styles.inputGroup}><label style={styles.label}>Amount</label><input style={styles.input} type="number" value={amount} onChange={(e) => setAmount(e.target.value)} /></div>
          <button type="submit" style={styles.submitBtn}><FaCheckCircle /> Submit</button>
        </form>
      </div>

      {/* History Table */}
      <div style={styles.card}>
        <div style={styles.title}><FaHistory /> Submission History ({filteredSubmissions.length} records)</div>
        <div style={styles.tableWrapper}>
          <table style={styles.table}>
            <thead>
              <tr>
                <th style={styles.th}>Date</th>
                <th style={styles.th}>Description</th>
                <th style={styles.th}>Type</th>
                <th style={styles.th}>Amount</th>
                <th style={styles.th}>Role</th>
                <th style={styles.th}>Action</th>
              </tr>
            </thead>
            <tbody>
              {filteredSubmissions.map((item) => (
                <tr key={item._id}>
                  <td style={styles.td}>{new Date(item.date).toLocaleDateString()}</td>
                  <td style={styles.td}>{item.description}</td>
                  <td style={styles.td}><span style={item.type === "Expense" ? styles.badgeExpense : styles.badgeIncome}>{item.type}</span></td>
                  <td style={styles.td}>₱{item.amount.toLocaleString()}</td>
                  <td style={styles.td}><span style={{fontSize: "11px", color: "#666", textTransform: "uppercase"}}>{item.role || "Employee"}</span></td>
                  <td style={styles.td}>
                    {/* EDIT AND DELETE BUTTONS ARE SIDE-BY-SIDE HERE */}
                    <div style={{ display: "flex", gap: "12px", alignItems: "center" }}>
                      <button onClick={() => openEditModal(item)} style={{ ...styles.actionBtn, color: "#4e73df" }} title="Edit">
                        <FaEdit />
                      </button>
                      <button onClick={() => deleteRecord(item._id)} style={{ ...styles.actionBtn, color: "#ff6b6b" }} title="Delete">
                        <FaTrash />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ReportsPage;